[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
]
test = "test"
script = "script"

[dependencies]
"@openzeppelin/contracts" = "4.9.3"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
